---
- hosts: webserver
  become: true
  tasks:
  - name: update the apt-get repo
    command: sudo apt-get update
  - name: Install maven on worker nodes
    package: name=maven state=present
  - name: Install Apache2
    package: name=apache2 state=latest
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
