---
- name: Update packages
  hosts: webserver
  become: true
  tasks:
    - name: Clone Java Project to the Server
      git:
        repo: https://github.com/maryjanebarger/jenkins-ansible-war-to-tomcat.git
        dest: /tmp/war_dir

    - name: Change directories to the project and build .war file
      shell: mvn clean package
      args:
        chdir: /tmp/war_dir

    - name: Rename war file
      shell: cd /tmp/war_dir/target && mv *.war /tmp/war_dir/target/myweb.war

    - name: copy war file to tomcat
      copy:
        src: /tmp/war_dir/target/myweb.war
        dest: /opt/tomcat/webapps/myweb.war remote_src=yes
      notify:
        - stop tomcat
        - start tomcat
