---
- name: Update packages
  hosts: localhost
  tasks:
    - name: Clone Java Project to the Server
      git:
        repo: https://github.com/maryjanebarger/jenkins-ansible-war-to-tomcat.git
        dest: /tmp/war_dir
      become: yes

    - name: Change directories to the project and build .war file
      shell: cd /tmp/war_dir
      become: yes

    - name: Change directories to the project and build .war file
      shell: mvn clean package
      args:
        chdir: /tmp/war_dir
      become: yes

    - name: Rename war file
      become: yes
      shell: cd /tmp/war_dir/target && mv *.war /tmp/war_dir/target/myweb.war
