---
- name: Update packages
  hosts: webserver
  become: true
  vars:
    ansible_become_user: admin
    ansible_ssh_user: jenkins
    ansible_ssh_private_key_file: /home/labsuser/.ssh/id_rsa
  tasks:
    - name: Clone Java Project to the Server
      git:
        repo: https://github.com/maryjanebarger/jenkins-ansible-war-to-tomcat.git
        dest: /tmp/war_dir

    - name: Change directories to the project and build .war file
      shell: mvn clean package
      args:
        chdir: /tmp/war_dir

    - name: Rename war file
      shell: cd /tmp/war_dir/target && mv *.war /tmp/war_dir/target/myweb.war
