---
- name: Update packages
  hosts: localhost  # Target the localhost as it's a local operation
  tasks:
    - name: Update packages on macOS using Homebrew
      become: no
      command: brew update
      when: ansible_system == 'Darwin'

    - name: Verify Maven installation
      command: mvn --version
      register: maven_version_output
      changed_when: false  # Mark as not changed to prevent unnecessary runs

    - name: Display Maven version
      debug:
        var: maven_version_output.stdout_lines

    - name: Clone or Copy Java Project to the local Server
      git:
        repo: https://github.com/maryjanebarger/jenkins-ansible-war-to-tomcat.git
        dest: /tmp/war_dir

    - name: Change Directory to the Project and create .war file
      become_user: libsuser
      become_method: su
      become: yes
      shell: cd /tmp/war_dir && mvn clean package
