---
- name: Update packages
  hosts: localhost
  tasks:
    - name: Clone Java Project to the Server
      become: yes
      git:
        repo: https://github.com/maryjanebarger/jenkins-ansible-war-to-tomcat.git
        dest: /tmp/war_dir

    - name: Change directories to the project and build .war file
#       become_user: labsuser
      become_method: su
      become: yes
      shell: cd /tmp/war_dir && mvn clean package

    - name: Rename war file
      become: yes
      shell: cd /tmp/war_dir/target && mv *.war /tmp/war_dir/target/myweb.war
