---
- name: Update packages
  hosts: localhost
  tasks:
    - name: Update packages on master node
      become: yes
      apt: pkg={{ item }}
      with_items:
        - maven
        - apache2

    - name: Verify Maven installation
      command: mvn --version
      register: maven_version_output
      changed_when: false       # Mark as not changed to prevent unnecessary runs

    - name: Display Maven version
      debug:
        var: maven_version_output.stdout_lines

    - name: Clone Java Project to the Server
      git:
        repo: https://github.com/maryjanebarger/jenkins-ansible-war-to-tomcat.git
        dest: /tmp/war_dir

    - name: Change irectories to the project and build .war file
#       become_user: labsuser
#      become_method: su
      become: yes
      shell: cd /tmp/war_dir && mvn clean package

    - name: Rename war file
      become: yes
      shell: cd /tmp/war_dir/target && mv *.war /tmp/war_dir/target/myweb.war
